language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - php5-cli
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmosquitto0 libmosquitto0-dev
  - export CXX=g++-4.8
script:
  - ./autogen.sh --enable-coverage && make all test
  - (cd src/lib/ebus/test && ./test_symbol && ./test_filereader && ./test_data && ./test_message)
  - (cd src/lib/ebus/contrib/test && ./test_contrib)
  - ./src/ebusd/ebusd --help
  - ./test_coverage.sh
after_success:
  - find . -type f -name '*.gcno' -exec bash -c "(f={}; ls -l \$f; cd \${f%/*}; gcov-4.8 -pb \${f##*/})" \;
  - bash <(curl -s https://codecov.io/bash) -X gcov
